version: '3.8'

services:
  web:
    image: ivanhd/prak-26:${TAG:-latest}
    build:
      context: .
      target: prod
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app