version: '3.8'

services:
  app:
    container_name: alta_cc
    build: .
    env_file:
      - .env
    networks:
      - alta_cc_network
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    restart: on-failure
    depends_on:
      - db
  db:
    container_name: alta_cc_db
    image: mysql:8-debian
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - alta_cc_network
    ports:
      - 3306:3306
    volumes:
      - mysql-db:/root/lib/data

volumes:
  mysql-db:

networks:
  alta_cc_network:
    driver: bridge